import { User, Organization, Task, Notification, Reminder } from "@/types";

export const mockUsers: User[] = [
  {
    id: "u1",
    email: "admin@tasky.io",
    name: "Sarah Chen",
    avatar: "",
    role: "admin",
    organizationId: "org1",
    createdAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "u2",
    email: "user@tasky.io",
    name: "Alex Rivera",
    avatar: "",
    role: "user",
    organizationId: "org1",
    createdAt: "2025-02-01T10:00:00Z",
  },
  {
    id: "u3",
    email: "jane@tasky.io",
    name: "Jane Smith",
    avatar: "",
    role: "user",
    organizationId: "org1",
    createdAt: "2025-02-10T10:00:00Z",
  },
  {
    id: "u4",
    email: "mike@tasky.io",
    name: "Mike Johnson",
    avatar: "",
    role: "user",
    organizationId: "org2",
    createdAt: "2025-03-01T10:00:00Z",
  },
];

export const mockOrganizations: Organization[] = [
  {
    id: "org1",
    name: "Acme Corp",
    description: "Building the future of productivity",
    inviteCode: "ACME-2025",
    ownerId: "u1",
    memberIds: ["u1", "u2", "u3"],
    createdAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "org2",
    name: "Startup Labs",
    description: "Innovation-driven team",
    inviteCode: "SLAB-2025",
    ownerId: "u4",
    memberIds: ["u4"],
    createdAt: "2025-03-01T10:00:00Z",
  },
];

export const mockTasks: Task[] = [
  {
    id: "t1",
    title: "Design system setup",
    description: "Create foundational design tokens and component library",
    status: "done",
    priority: "high",
    assigneeId: "u2",
    creatorId: "u1",
    organizationId: "org1",
    dueDate: "2025-03-01",
    tags: ["design", "foundation"],
    createdAt: "2025-02-15T10:00:00Z",
    updatedAt: "2025-02-28T10:00:00Z",
  },
  {
    id: "t2",
    title: "API integration layer",
    description: "Build REST API integration with error handling",
    status: "in-progress",
    priority: "high",
    assigneeId: "u3",
    creatorId: "u1",
    organizationId: "org1",
    dueDate: "2025-03-10",
    tags: ["backend", "api"],
    createdAt: "2025-02-20T10:00:00Z",
    updatedAt: "2025-03-01T10:00:00Z",
  },
  {
    id: "t3",
    title: "User onboarding flow",
    description: "Implement role-based onboarding with smart questions",
    status: "in-progress",
    priority: "medium",
    assigneeId: "u2",
    creatorId: "u1",
    organizationId: "org1",
    dueDate: "2025-03-08",
    tags: ["ux", "onboarding"],
    createdAt: "2025-02-22T10:00:00Z",
    updatedAt: "2025-03-02T10:00:00Z",
  },
  {
    id: "t4",
    title: "Dashboard analytics widgets",
    description: "Build chart components for the admin dashboard",
    status: "todo",
    priority: "medium",
    assigneeId: "u2",
    creatorId: "u1",
    organizationId: "org1",
    dueDate: "2025-03-15",
    tags: ["analytics", "dashboard"],
    createdAt: "2025-03-01T10:00:00Z",
    updatedAt: "2025-03-01T10:00:00Z",
  },
  {
    id: "t5",
    title: "Mobile responsive polish",
    description: "Ensure all pages work perfectly on mobile devices",
    status: "todo",
    priority: "low",
    assigneeId: "u3",
    creatorId: "u1",
    organizationId: "org1",
    dueDate: "2025-03-20",
    tags: ["mobile", "responsive"],
    createdAt: "2025-03-01T10:00:00Z",
    updatedAt: "2025-03-01T10:00:00Z",
  },
  {
    id: "t6",
    title: "Write unit tests",
    description: "Add comprehensive test coverage for core features",
    status: "review",
    priority: "high",
    assigneeId: "u3",
    creatorId: "u1",
    organizationId: "org1",
    dueDate: "2025-03-12",
    tags: ["testing", "quality"],
    createdAt: "2025-02-25T10:00:00Z",
    updatedAt: "2025-03-03T10:00:00Z",
  },
  {
    id: "t7",
    title: "Personal task: Read docs",
    description: "Go through the new framework documentation",
    status: "todo",
    priority: "low",
    assigneeId: "u2",
    creatorId: "u2",
    tags: ["personal", "learning"],
    createdAt: "2025-03-02T10:00:00Z",
    updatedAt: "2025-03-02T10:00:00Z",
  },
  {
    id: "t8",
    title: "Security audit",
    description: "Review authentication flow and permissions",
    status: "todo",
    priority: "urgent",
    assigneeId: "u1",
    creatorId: "u1",
    organizationId: "org1",
    dueDate: "2025-03-05",
    tags: ["security", "audit"],
    createdAt: "2025-03-01T10:00:00Z",
    updatedAt: "2025-03-01T10:00:00Z",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    userId: "u2",
    title: "Task Reminder",
    message: "Don't forget to complete 'User onboarding flow' by March 8th",
    type: "reminder",
    read: false,
    taskId: "t3",
    createdAt: "2025-03-04T09:00:00Z",
  },
  {
    id: "n2",
    userId: "u2",
    title: "New Task Assigned",
    message: "You've been assigned 'Dashboard analytics widgets'",
    type: "assignment",
    read: false,
    taskId: "t4",
    createdAt: "2025-03-03T14:00:00Z",
  },
  {
    id: "n3",
    userId: "u3",
    title: "Task Reminder",
    message: "API integration layer is due on March 10th",
    type: "reminder",
    read: true,
    taskId: "t2",
    createdAt: "2025-03-02T10:00:00Z",
  },
  {
    id: "n4",
    userId: "u1",
    title: "Task Completed",
    message: "Alex Rivera completed 'Design system setup'",
    type: "update",
    read: false,
    taskId: "t1",
    createdAt: "2025-03-01T16:00:00Z",
  },
];

export const mockReminders: Reminder[] = [
  {
    id: "r1",
    taskId: "t3",
    senderId: "u1",
    recipientId: "u2",
    message: "Please complete the onboarding flow by Friday",
    organizationId: "org1",
    createdAt: "2025-03-04T09:00:00Z",
  },
];
